<?php

/**
 * @file
 * Primary module hooks for Repo Nodes module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_form_FORM_ID_alter() for our user profile form.
 */
function repo_nodes_form_user_form_alter(array &$form, FormStateInterface $formState, string $form_id): void {
  if (!empty($form['field_repository_url']['widget'])) {
    foreach (Element::children($form['field_repository_url']['widget']) as $el_index) {
      $form['field_repository_url']['widget'][$el_index]['#process'][] = '_repo_nodes_url_help_text';
    }
  }
}

/**
 * Custom function to populate the Repository URL descriptions.
 *
 * @param array<mixed> $element
 *   The element to modify.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 * @param array<mixed> $form
 *   The form array.
 *
 * @return array<mixed>
 *   A render element.
 */
function repo_nodes_url_help_text(array $element, FormStateInterface $form_state, array &$form): array {
  /** @var \Drupal\repo_nodes\RepoNodesService $repository_service */
  $repository_service = \Drupal::service('repo_nodes.service');
  $help_text = $repository_service->getValidatorHelpText();
  if ($help_text) {
    $element['uri']['#description'] = t('Valid URLs are: %help_text', ['%help_text' => $help_text]);
  }
  else {
    $element['uri']['#description'] = t('No repository plugins are enabled. Contact site administrator.');
  }
  $element['uri']['#description_display'] = 'before';
  return $element;
}


